os: linux
dist: trusty
sudo: required

install:
- sudo apt-get install -y uidmap
- echo 'deb [arch=amd64 trusted=yes] https://ubuntu.zerogw.com vagga main' | sudo tee /etc/apt/sources.list.d/vagga.list
- sudo apt-get update
- sudo apt-get install vagga
- |
  echo "cache-dir: ~/.cache/vagga" >> ~/.vagga.yaml
  echo "ubuntu-mirror: http://mirrors.us.kernel.org/ubuntu/" >> ~/.vagga.yaml
  echo "alpine-mirror: http://mirrors.gigenet.com/alpinelinux/" >> ~/.vagga.yaml

before_script:
- vagga _build java

script:
- |
  GRADLE_ARGS="--info --stacktrace --no-daemon"
  if [[ $TRAVIS_TAG == v* ]]; then
    GRADLE_ARGS="$GRADLE_ARGS -Prelease=true"
  fi
  if [[ $TRAVIS_TAG == v*-es* ]]; then
    ES_VERSION=$(echo $TRAVIS_TAG | sed 's/v.*-es\(.*\)/\1/')
    GRADLE_ARGS="$GRADLE_ARGS -PesVersion=$ES_VERSION"
  fi
  vagga assemble $GRADLE_ARGS
  vagga gradle updateSHAs $GRADLE_ARGS
  vagga check $GRADLE_ARGS -x integTest

after_success:
- |
  if [[ -v ES_VERSION ]]; then
    vagga -e BINTRAY_USER -e BINTRAY_API_KEY gradle bintrayUpload $GRADLE_ARGS
  fi

cache:
  directories:
  - $HOME/.cache/vagga/gradle-cache
