install:
- choco install gradle --version 2.13
- set PATH=C:\tools\Gradle\bin;%PATH%
- set JAVA_TOOL_OPTIONS=-Dfile.encoding=UTF8
- gradle -version

build_script:
- gradle assemble --no-daemon

test_script:
- gradle test --no-daemon

cache:
- C:\ProgramData\chocolatey\bin -> appveyor.yml
- C:\ProgramData\chocolatey\lib -> appveyor.yml
- C:\Users\appveyor\.gradle
